### ISSUE TITLE
Letsencrypt error

### ISSUE THREAD

**Issue by DylanPiercey** [Daplie/node-greenlock#65]
Looks like they updated their api, I am getting this error:

```console
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok

{ type: 'urn:acme:error:malformed',
  detail: 'Parse error reading JWS',
  status: 400 }
```

Is there a work around?

**Comment by Akashfinocial** [comment]
npm WARN deprecated letsencrypt@2.1.8:letsencrypt has been renamed to greenlock. Please find it at npm greenlock

how to solve this error

**Comment by coolaj86** [comment]
Yes, it was renamed to greenlock and here's the official project page: <https://git.coolaj86.com/coolaj86/greenlock.js>
