### ISSUE TITLE
[Docker] - This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand

### ISSUE THREAD

**Issue by lightswitchr** [Daplie/node-greenlock#68]
I'm running greenlock as part of a node app in docker on my development machine, so therefore I am using the LE `staging` server.

If I access the server directly through `192.168.99.100`, the app is served and I get a fake certificate, however I set up an A record in my DNS which points to `192.168.99.100` in order to test Facebook and Twitter callbacks - Facebook doesn't allow IP URLs. I also placed this domain into the `opts.domains` array.

When I visit my site locally though this domain address, the app no longer gets served (`Site cannot be reached` in the browser) and I get the following error:

```
web_1         | This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand
web_1         | { hkCUwtaTjcY: 'https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417',
web_1         |   'key-change': 'https://acme-staging.api.letsencrypt.org/acme/key-change',
web_1         |   'new-authz': 'https://acme-staging.api.letsencrypt.org/acme/new-authz',
web_1         |   'new-cert': 'https://acme-staging.api.letsencrypt.org/acme/new-cert',
web_1         |   'new-reg': 'https://acme-staging.api.letsencrypt.org/acme/new-reg',
web_1         |   'revoke-cert': 'https://acme-staging.api.letsencrypt.org/acme/revoke-cert' }
```

Why is this happening and how can I resolve it? Note that accessing the site though the IP works fine.

**Comment by cpu** [comment]
> Why is this happening and how can I resolve it? Note that accessing the site though the IP works fine.

The reason this is breaking is [explained in the linked community forum post](https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417). 

If this isn't a warning message but an actual error then the only way to resolve it will be with an update to the `node-greenlock` code. The client should ignore `/directory` entries it doesn't understand instead of treating it as an error condition.

**Comment by lightswitchr** [comment]
I've no idea if it's an error or a warning, but the fact that `node-greenlock` doesn't actually serve any pages when this happens points to an error to me.

**Comment by lightswitchr** [comment]
I realised this is the wrong repository for the software I'm using - I've opened another issue [here](https://git.daplie.com/Daplie/greenlock-express/issues/124).

**Comment by jsha** [comment]
@lightswitchr can you post a link from https://git.daplie.com/Daplie/greenlock-express/issues/124 to this conversation and summarize the information @cpu provided above? I think that will help the maintainers of greenlock-express find a solution more quickly.

**Comment by coolaj86** [comment]
For those tracking this, it has long since been fixed over at the official repository:
<https://git.coolaj86.com/coolaj86/greenlock.js>
